### ISSUE TITLE
when i processiong global placement, an Error occur,how to fix this problem?

### ISSUE THREAD

**Issue by imcamino** [limbo018/DREAMPlace#125]
![image](https://user-images.githubusercontent.com/122084694/230644318-ebf2c87f-b9d8-4b19-8132-5e0c4ce4ee43.png)

**Comment by limbo018** [comment]
Hi, you may check out ```develop``` branch. The problem comes from higher python version. We have fixed it. 

https://github.com/limbo018/DREAMPlace/blob/8e9f599084e0658f81a1e29706594e55a8060a82/dreamplace/PlaceDB.py#L576

**Comment by imcamino** [comment]
Thanks for your help. i already change to dev branch. but the problem still exists.

**Comment by imcamino** [comment]
![image](https://user-images.githubusercontent.com/122084694/230706617-1ef99d65-e3b7-400e-9c99-6ef4947c8aa9.png)
I think the Exception is the critical problem instead of the warnning

**Comment by limbo018** [comment]
It looks like you have changed the code? (you wrap it in the subprocess) Does it original version of code run?

**Comment by imcamino** [comment]
Yep.i just wrap it in a Entry script。 Actually It works for ISPD case，but fail to run other case come from open source。

**Comment by limbo018** [comment]
If you can share the LEF/DEF files of your case, I can help take a look. There might some problem when reading the design.

**Comment by imcamino** [comment]
[test_case.zip](https://github.com/limbo018/DREAMPlace/files/11185711/test_case.zip)
There is one of my case.

**Comment by imcamino** [comment]
is there any problem in this design?

**Comment by limbo018** [comment]
I will take a look during the weekend. Quite busy this week. 







                       
Original
                       
                     

From:"imcamino"< ***@***.*** &gt;;

Date:2023/4/12 9:04

To:"limbo018/DREAMPlace"< ***@***.*** &gt;;

CC:"Yibo Lin"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [limbo018/DREAMPlace] when i processiong global placement, anError occur,how to fix this problem? (Issue #125)




 
is there any problem in this design?
 
&mdash;

**Comment by imcamino** [comment]
Ok,  I appreciate your time.

**Comment by limbo018** [comment]
Hi, I just took a look at your DEF file. The ```COMPONENTS``` section is missing.

**Comment by imcamino** [comment]
Thanks for your reply. i will write the def out with unplaced stdcell & try.
