### ISSUE TITLE
Reading issue with lef for NanGate45

### ISSUE THREAD

**Issue by nineight908** [limbo018/DREAMPlace#194]
Hello professor, when I try to use NanGate45's lef file as input lef, I get a Segmentation fault (core dumped) error.
<img width="619" alt="微信图片_20241022155805" src="https://github.com/user-attachments/assets/aa460b84-32fa-4292-8a25-96912fa64aa1">
Here are my lef files and def files：
<img width="617" alt="微信图片_20241022160946" src="https://github.com/user-attachments/assets/ea53395b-2ff2-4202-81d6-0af5a13dcf53">
Looking forward to hearing from you, thank you.

**Comment by limbo018** [comment]
Can you share your case? You can upload here or email me.

**Comment by Constwelve** [comment]
The previous version would crash when processing def pins with ports. This issue has now been resolved in the latest commit on the develop branch.

**Comment by limbo018** [comment]
Please check commit https://github.com/limbo018/DREAMPlace/commit/daaa03fe644a80922eedb6842fdd1fef34cdd555

**Comment by nineight908** [comment]
@limbo018 @Constwelve Hello professors, thank you for taking time out of your busy schedule to answer my questions, but I still have problems in the experiment, how can I solve them?
<img width="677" alt="微信图片_20241024164915" src="https://github.com/user-attachments/assets/a3f88ac9-b06f-486e-bea5-347beab3c0a2">

**Comment by Constwelve** [comment]
Too many movable macros (123692) caused the macro legalizer to fail to find a legal solution. If you prefer not to change the algorithm, I suggest merging some macros or fixing them manually.

**Comment by nineight908** [comment]
I've tried to pin a part of the components in the def file, but I still get the above problem, is there any other solution?
